// Code generated by protoc-gen-go.
// source: account.proto
// DO NOT EDIT!

/*
Package notekeeper is a generated protocol buffer package.

It is generated from these files:
	account.proto
	collection.proto
	common.proto
	db.proto
	kex.proto
	note.proto
	notebook.proto
	rpc.proto
	shelf.proto
	tag.proto
	title.proto
	ui_state.proto
	workspace.proto

It has these top-level messages:
	AccountStateResponse
	CreateAccountRequest
	UserId
	UserIdResponse
	UnlockAccountRequest
	SigninAccountRequest
	Collection
	GetCollectionsRequest
	GetCollectionsResponse
	CreateCollectionRequest
	SaveCollectionRequest
	DeleteCollectionRequest
	RequestHeader
	ResponseHeader
	OpenMasterDbRequest
	KeyExchangeRequest
	KeyExchangeResponse
	Note
	CreateNoteRequest
	SaveNoteRequest
	DeleteNoteRequest
	LoadNoteRequest
	LoadNoteResponse
	GetNotesRequest
	GetNotesResponse
	Notebook
	CreateNotebookRequest
	SaveNotebookRequest
	GetNotebooksRequest
	GetNotebooksResponse
	DeleteNotebookRequest
	EmptyRequest
	EmptyResponse
	IdRequest
	IdResponse
	Shelf
	GetShelvesRequest
	GetShelvesResponse
	CreateShelfRequest
	SaveShelfRequest
	DeleteShelfRequest
	Tag
	GetTagsRequest
	GetTagsResponse
	CreateTagRequest
	SaveTagRequest
	DeleteTagRequest
	Title
	LoadUIStateResponse
	SaveUIStateRequest
*/
package notekeeper

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AccountStateResponse struct {
	Header   *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	SignedIn bool            `protobuf:"varint,2,opt,name=signedIn" json:"signedIn,omitempty"`
	Locked   bool            `protobuf:"varint,3,opt,name=locked" json:"locked,omitempty"`
	Exists   bool            `protobuf:"varint,4,opt,name=exists" json:"exists,omitempty"`
}

func (m *AccountStateResponse) Reset()                    { *m = AccountStateResponse{} }
func (m *AccountStateResponse) String() string            { return proto.CompactTextString(m) }
func (*AccountStateResponse) ProtoMessage()               {}
func (*AccountStateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AccountStateResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *AccountStateResponse) GetSignedIn() bool {
	if m != nil {
		return m.SignedIn
	}
	return false
}

func (m *AccountStateResponse) GetLocked() bool {
	if m != nil {
		return m.Locked
	}
	return false
}

func (m *AccountStateResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

type CreateAccountRequest struct {
	Header     *RequestHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Name       string         `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Email      string         `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Passphrase string         `protobuf:"bytes,4,opt,name=passphrase" json:"passphrase,omitempty"`
}

func (m *CreateAccountRequest) Reset()                    { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()               {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateAccountRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *CreateAccountRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateAccountRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateAccountRequest) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

type UserId struct {
	AccountId string `protobuf:"bytes,1,opt,name=accountId" json:"accountId,omitempty"`
	UserId    string `protobuf:"bytes,2,opt,name=userId" json:"userId,omitempty"`
}

func (m *UserId) Reset()                    { *m = UserId{} }
func (m *UserId) String() string            { return proto.CompactTextString(m) }
func (*UserId) ProtoMessage()               {}
func (*UserId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UserId) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *UserId) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type UserIdResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	User   *UserId         `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
}

func (m *UserIdResponse) Reset()                    { *m = UserIdResponse{} }
func (m *UserIdResponse) String() string            { return proto.CompactTextString(m) }
func (*UserIdResponse) ProtoMessage()               {}
func (*UserIdResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UserIdResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *UserIdResponse) GetUser() *UserId {
	if m != nil {
		return m.User
	}
	return nil
}

type UnlockAccountRequest struct {
	Header     *RequestHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Id         string         `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Passphrase string         `protobuf:"bytes,3,opt,name=passphrase" json:"passphrase,omitempty"`
}

func (m *UnlockAccountRequest) Reset()                    { *m = UnlockAccountRequest{} }
func (m *UnlockAccountRequest) String() string            { return proto.CompactTextString(m) }
func (*UnlockAccountRequest) ProtoMessage()               {}
func (*UnlockAccountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UnlockAccountRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *UnlockAccountRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UnlockAccountRequest) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

type SigninAccountRequest struct {
	Header     *RequestHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Name       string         `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Email      string         `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Passphrase string         `protobuf:"bytes,4,opt,name=passphrase" json:"passphrase,omitempty"`
}

func (m *SigninAccountRequest) Reset()                    { *m = SigninAccountRequest{} }
func (m *SigninAccountRequest) String() string            { return proto.CompactTextString(m) }
func (*SigninAccountRequest) ProtoMessage()               {}
func (*SigninAccountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SigninAccountRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SigninAccountRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SigninAccountRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SigninAccountRequest) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

func init() {
	proto.RegisterType((*AccountStateResponse)(nil), "notekeeper.AccountStateResponse")
	proto.RegisterType((*CreateAccountRequest)(nil), "notekeeper.CreateAccountRequest")
	proto.RegisterType((*UserId)(nil), "notekeeper.UserId")
	proto.RegisterType((*UserIdResponse)(nil), "notekeeper.UserIdResponse")
	proto.RegisterType((*UnlockAccountRequest)(nil), "notekeeper.UnlockAccountRequest")
	proto.RegisterType((*SigninAccountRequest)(nil), "notekeeper.SigninAccountRequest")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x92, 0xc1, 0x4e, 0x3a, 0x31,
	0x10, 0xc6, 0xb3, 0xc0, 0x7f, 0xc3, 0x0e, 0x7f, 0x39, 0x34, 0x1b, 0xb3, 0x12, 0x63, 0xc8, 0x1e,
	0x0c, 0x27, 0x12, 0xf1, 0x6e, 0x62, 0xbc, 0xc8, 0xb5, 0x84, 0x07, 0xa8, 0xdb, 0x09, 0x34, 0xb0,
	0xed, 0xda, 0x96, 0x44, 0x9f, 0xc3, 0xc4, 0xe7, 0x35, 0x3b, 0x2d, 0x82, 0x78, 0xe4, 0xe2, 0x6d,
	0xbf, 0x99, 0xaf, 0xb3, 0xbf, 0x7e, 0x53, 0xb8, 0x10, 0x55, 0x65, 0x76, 0xda, 0x4f, 0x1b, 0x6b,
	0xbc, 0x61, 0xa0, 0x8d, 0xc7, 0x0d, 0x62, 0x83, 0x76, 0xf4, 0xbf, 0x32, 0x75, 0x6d, 0x74, 0xe8,
	0x94, 0x9f, 0x09, 0xe4, 0x8f, 0xc1, 0xbb, 0xf0, 0xc2, 0x23, 0x47, 0xd7, 0x18, 0xed, 0x90, 0xcd,
	0x20, 0x5d, 0xa3, 0x90, 0x68, 0x8b, 0x64, 0x9c, 0x4c, 0x06, 0xb3, 0xd1, 0xf4, 0x30, 0x63, 0xba,
	0x77, 0x3d, 0x93, 0x83, 0x47, 0x27, 0x1b, 0x41, 0xdf, 0xa9, 0x95, 0x46, 0x39, 0xd7, 0x45, 0x67,
	0x9c, 0x4c, 0xfa, 0xfc, 0x5b, 0xb3, 0x4b, 0x48, 0xb7, 0xa6, 0xda, 0xa0, 0x2c, 0xba, 0xd4, 0x89,
	0xaa, 0xad, 0xe3, 0x9b, 0x72, 0xde, 0x15, 0xbd, 0x50, 0x0f, 0xaa, 0xfc, 0x48, 0x20, 0x7f, 0xb2,
	0x28, 0x3c, 0x46, 0x3c, 0x8e, 0xaf, 0x3b, 0x74, 0x9e, 0xdd, 0x9d, 0x80, 0x5d, 0xfd, 0x04, 0x23,
	0xd3, 0x09, 0x17, 0x83, 0x9e, 0x16, 0x35, 0x12, 0x53, 0xc6, 0xe9, 0x9b, 0xe5, 0xf0, 0x0f, 0x6b,
	0xa1, 0xb6, 0x84, 0x93, 0xf1, 0x20, 0xd8, 0x0d, 0x40, 0x23, 0x9c, 0x6b, 0xd6, 0x56, 0x38, 0x24,
	0xa2, 0x8c, 0x1f, 0x55, 0xca, 0x07, 0x48, 0x97, 0x0e, 0xed, 0x5c, 0xb2, 0x6b, 0xc8, 0x62, 0xc6,
	0x73, 0x49, 0x24, 0x19, 0x3f, 0x14, 0xda, 0x5b, 0xed, 0xc8, 0x17, 0xff, 0x19, 0x55, 0xb9, 0x85,
	0x61, 0x38, 0x7f, 0x56, 0xce, 0xb7, 0xd0, 0x6b, 0xe7, 0xd1, 0xec, 0xc1, 0x8c, 0x1d, 0x9f, 0x88,
	0xd3, 0xa9, 0x5f, 0xbe, 0x43, 0xbe, 0xd4, 0x6d, 0xce, 0xe7, 0x47, 0x38, 0x84, 0x8e, 0xda, 0x5f,
	0xa6, 0xa3, 0xe4, 0x49, 0x50, 0xdd, 0x5f, 0x41, 0xb5, 0xeb, 0x5b, 0xa8, 0x95, 0x56, 0xfa, 0x0f,
	0xad, 0xef, 0x25, 0xa5, 0x47, 0x7f, 0xff, 0x15, 0x00, 0x00, 0xff, 0xff, 0xe7, 0xa5, 0xae, 0xe3,
	0x1f, 0x03, 0x00, 0x00,
}
