// Code generated by protoc-gen-go.
// source: backend.proto
// DO NOT EDIT!

/*
Package notekeeper is a generated protocol buffer package.

It is generated from these files:
	backend.proto

It has these top-level messages:
	StatusResponse
	TokenRequest
	IdRequest
	IdResponse
	UIStateResponse
	SaveUIStateRequest
	AccountStateResponse
	OpenMasterDbRequest
	CreateAccountRequest
	UnlockAccountRequest
	SigninAccountRequest
	CreateNotebookRequest
*/
package notekeeper

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// a generic RPC response message when we only need a status returned
type StatusResponse struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Code   int32  `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
}

func (m *StatusResponse) Reset()                    { *m = StatusResponse{} }
func (m *StatusResponse) String() string            { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()               {}
func (*StatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StatusResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *StatusResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

// a generic RPC request message
type TokenRequest struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *TokenRequest) Reset()                    { *m = TokenRequest{} }
func (m *TokenRequest) String() string            { return proto.CompactTextString(m) }
func (*TokenRequest) ProtoMessage()               {}
func (*TokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// a generic RPC request message containing a common UUID string
type IdRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *IdRequest) Reset()                    { *m = IdRequest{} }
func (m *IdRequest) String() string            { return proto.CompactTextString(m) }
func (*IdRequest) ProtoMessage()               {}
func (*IdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *IdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// a generic RPC response message containing a common UUID string and status
type IdResponse struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	Code   int32  `protobuf:"varint,3,opt,name=code" json:"code,omitempty"`
}

func (m *IdResponse) Reset()                    { *m = IdResponse{} }
func (m *IdResponse) String() string            { return proto.CompactTextString(m) }
func (*IdResponse) ProtoMessage()               {}
func (*IdResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *IdResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *IdResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *IdResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type UIStateResponse struct {
	Status       *StatusResponse `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	WindowWidth  int32           `protobuf:"varint,2,opt,name=windowWidth" json:"windowWidth,omitempty"`
	WindowHeight int32           `protobuf:"varint,3,opt,name=windowHeight" json:"windowHeight,omitempty"`
}

func (m *UIStateResponse) Reset()                    { *m = UIStateResponse{} }
func (m *UIStateResponse) String() string            { return proto.CompactTextString(m) }
func (*UIStateResponse) ProtoMessage()               {}
func (*UIStateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UIStateResponse) GetStatus() *StatusResponse {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *UIStateResponse) GetWindowWidth() int32 {
	if m != nil {
		return m.WindowWidth
	}
	return 0
}

func (m *UIStateResponse) GetWindowHeight() int32 {
	if m != nil {
		return m.WindowHeight
	}
	return 0
}

type SaveUIStateRequest struct {
	Status       *StatusResponse `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	WindowWidth  int32           `protobuf:"varint,2,opt,name=windowWidth" json:"windowWidth,omitempty"`
	WindowHeight int32           `protobuf:"varint,3,opt,name=windowHeight" json:"windowHeight,omitempty"`
}

func (m *SaveUIStateRequest) Reset()                    { *m = SaveUIStateRequest{} }
func (m *SaveUIStateRequest) String() string            { return proto.CompactTextString(m) }
func (*SaveUIStateRequest) ProtoMessage()               {}
func (*SaveUIStateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SaveUIStateRequest) GetStatus() *StatusResponse {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SaveUIStateRequest) GetWindowWidth() int32 {
	if m != nil {
		return m.WindowWidth
	}
	return 0
}

func (m *SaveUIStateRequest) GetWindowHeight() int32 {
	if m != nil {
		return m.WindowHeight
	}
	return 0
}

type AccountStateResponse struct {
	SignedIn bool `protobuf:"varint,1,opt,name=signedIn" json:"signedIn,omitempty"`
	Locked   bool `protobuf:"varint,2,opt,name=locked" json:"locked,omitempty"`
}

func (m *AccountStateResponse) Reset()                    { *m = AccountStateResponse{} }
func (m *AccountStateResponse) String() string            { return proto.CompactTextString(m) }
func (*AccountStateResponse) ProtoMessage()               {}
func (*AccountStateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *AccountStateResponse) GetSignedIn() bool {
	if m != nil {
		return m.SignedIn
	}
	return false
}

func (m *AccountStateResponse) GetLocked() bool {
	if m != nil {
		return m.Locked
	}
	return false
}

type OpenMasterDbRequest struct {
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
}

func (m *OpenMasterDbRequest) Reset()                    { *m = OpenMasterDbRequest{} }
func (m *OpenMasterDbRequest) String() string            { return proto.CompactTextString(m) }
func (*OpenMasterDbRequest) ProtoMessage()               {}
func (*OpenMasterDbRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *OpenMasterDbRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type CreateAccountRequest struct {
	Name       string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Email      string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Passphrase string `protobuf:"bytes,3,opt,name=passphrase" json:"passphrase,omitempty"`
}

func (m *CreateAccountRequest) Reset()                    { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()               {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CreateAccountRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateAccountRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateAccountRequest) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

type UnlockAccountRequest struct {
	Id         string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Passphrase string `protobuf:"bytes,2,opt,name=passphrase" json:"passphrase,omitempty"`
}

func (m *UnlockAccountRequest) Reset()                    { *m = UnlockAccountRequest{} }
func (m *UnlockAccountRequest) String() string            { return proto.CompactTextString(m) }
func (*UnlockAccountRequest) ProtoMessage()               {}
func (*UnlockAccountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *UnlockAccountRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UnlockAccountRequest) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

type SigninAccountRequest struct {
	Name       string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Email      string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Passphrase string `protobuf:"bytes,3,opt,name=passphrase" json:"passphrase,omitempty"`
}

func (m *SigninAccountRequest) Reset()                    { *m = SigninAccountRequest{} }
func (m *SigninAccountRequest) String() string            { return proto.CompactTextString(m) }
func (*SigninAccountRequest) ProtoMessage()               {}
func (*SigninAccountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *SigninAccountRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SigninAccountRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SigninAccountRequest) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

type CreateNotebookRequest struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	UserId  string `protobuf:"bytes,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	ShelfId string `protobuf:"bytes,3,opt,name=shelf_id,json=shelfId" json:"shelf_id,omitempty"`
}

func (m *CreateNotebookRequest) Reset()                    { *m = CreateNotebookRequest{} }
func (m *CreateNotebookRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateNotebookRequest) ProtoMessage()               {}
func (*CreateNotebookRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *CreateNotebookRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateNotebookRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateNotebookRequest) GetShelfId() string {
	if m != nil {
		return m.ShelfId
	}
	return ""
}

func init() {
	proto.RegisterType((*StatusResponse)(nil), "notekeeper.StatusResponse")
	proto.RegisterType((*TokenRequest)(nil), "notekeeper.TokenRequest")
	proto.RegisterType((*IdRequest)(nil), "notekeeper.IdRequest")
	proto.RegisterType((*IdResponse)(nil), "notekeeper.IdResponse")
	proto.RegisterType((*UIStateResponse)(nil), "notekeeper.UIStateResponse")
	proto.RegisterType((*SaveUIStateRequest)(nil), "notekeeper.SaveUIStateRequest")
	proto.RegisterType((*AccountStateResponse)(nil), "notekeeper.AccountStateResponse")
	proto.RegisterType((*OpenMasterDbRequest)(nil), "notekeeper.OpenMasterDbRequest")
	proto.RegisterType((*CreateAccountRequest)(nil), "notekeeper.CreateAccountRequest")
	proto.RegisterType((*UnlockAccountRequest)(nil), "notekeeper.UnlockAccountRequest")
	proto.RegisterType((*SigninAccountRequest)(nil), "notekeeper.SigninAccountRequest")
	proto.RegisterType((*CreateNotebookRequest)(nil), "notekeeper.CreateNotebookRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Backend service

type BackendClient interface {
	OpenMasterDb(ctx context.Context, in *OpenMasterDbRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*IdResponse, error)
	UnlockAccount(ctx context.Context, in *UnlockAccountRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	SigninAccount(ctx context.Context, in *SigninAccountRequest, opts ...grpc.CallOption) (*IdResponse, error)
	SignoutAccount(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	LockAccount(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	UIState(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*UIStateResponse, error)
	SaveUIState(ctx context.Context, in *SaveUIStateRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	AccountState(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*AccountStateResponse, error)
	CreateNotebook(ctx context.Context, in *CreateNotebookRequest, opts ...grpc.CallOption) (*IdResponse, error)
}

type backendClient struct {
	cc *grpc.ClientConn
}

func NewBackendClient(cc *grpc.ClientConn) BackendClient {
	return &backendClient{cc}
}

func (c *backendClient) OpenMasterDb(ctx context.Context, in *OpenMasterDbRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := grpc.Invoke(ctx, "/notekeeper.Backend/OpenMasterDb", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*IdResponse, error) {
	out := new(IdResponse)
	err := grpc.Invoke(ctx, "/notekeeper.Backend/CreateAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) UnlockAccount(ctx context.Context, in *UnlockAccountRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := grpc.Invoke(ctx, "/notekeeper.Backend/UnlockAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) SigninAccount(ctx context.Context, in *SigninAccountRequest, opts ...grpc.CallOption) (*IdResponse, error) {
	out := new(IdResponse)
	err := grpc.Invoke(ctx, "/notekeeper.Backend/SigninAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) SignoutAccount(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := grpc.Invoke(ctx, "/notekeeper.Backend/SignoutAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) LockAccount(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := grpc.Invoke(ctx, "/notekeeper.Backend/LockAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) UIState(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*UIStateResponse, error) {
	out := new(UIStateResponse)
	err := grpc.Invoke(ctx, "/notekeeper.Backend/UIState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) SaveUIState(ctx context.Context, in *SaveUIStateRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := grpc.Invoke(ctx, "/notekeeper.Backend/SaveUIState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) AccountState(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*AccountStateResponse, error) {
	out := new(AccountStateResponse)
	err := grpc.Invoke(ctx, "/notekeeper.Backend/AccountState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) CreateNotebook(ctx context.Context, in *CreateNotebookRequest, opts ...grpc.CallOption) (*IdResponse, error) {
	out := new(IdResponse)
	err := grpc.Invoke(ctx, "/notekeeper.Backend/CreateNotebook", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Backend service

type BackendServer interface {
	OpenMasterDb(context.Context, *OpenMasterDbRequest) (*StatusResponse, error)
	CreateAccount(context.Context, *CreateAccountRequest) (*IdResponse, error)
	UnlockAccount(context.Context, *UnlockAccountRequest) (*StatusResponse, error)
	SigninAccount(context.Context, *SigninAccountRequest) (*IdResponse, error)
	SignoutAccount(context.Context, *IdRequest) (*StatusResponse, error)
	LockAccount(context.Context, *IdRequest) (*StatusResponse, error)
	UIState(context.Context, *TokenRequest) (*UIStateResponse, error)
	SaveUIState(context.Context, *SaveUIStateRequest) (*StatusResponse, error)
	AccountState(context.Context, *TokenRequest) (*AccountStateResponse, error)
	CreateNotebook(context.Context, *CreateNotebookRequest) (*IdResponse, error)
}

func RegisterBackendServer(s *grpc.Server, srv BackendServer) {
	s.RegisterService(&_Backend_serviceDesc, srv)
}

func _Backend_OpenMasterDb_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenMasterDbRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).OpenMasterDb(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notekeeper.Backend/OpenMasterDb",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).OpenMasterDb(ctx, req.(*OpenMasterDbRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notekeeper.Backend/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_UnlockAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).UnlockAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notekeeper.Backend/UnlockAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).UnlockAccount(ctx, req.(*UnlockAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_SigninAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SigninAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).SigninAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notekeeper.Backend/SigninAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).SigninAccount(ctx, req.(*SigninAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_SignoutAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).SignoutAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notekeeper.Backend/SignoutAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).SignoutAccount(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_LockAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).LockAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notekeeper.Backend/LockAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).LockAccount(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_UIState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).UIState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notekeeper.Backend/UIState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).UIState(ctx, req.(*TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_SaveUIState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveUIStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).SaveUIState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notekeeper.Backend/SaveUIState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).SaveUIState(ctx, req.(*SaveUIStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_AccountState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).AccountState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notekeeper.Backend/AccountState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).AccountState(ctx, req.(*TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_CreateNotebook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNotebookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).CreateNotebook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notekeeper.Backend/CreateNotebook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).CreateNotebook(ctx, req.(*CreateNotebookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Backend_serviceDesc = grpc.ServiceDesc{
	ServiceName: "notekeeper.Backend",
	HandlerType: (*BackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenMasterDb",
			Handler:    _Backend_OpenMasterDb_Handler,
		},
		{
			MethodName: "CreateAccount",
			Handler:    _Backend_CreateAccount_Handler,
		},
		{
			MethodName: "UnlockAccount",
			Handler:    _Backend_UnlockAccount_Handler,
		},
		{
			MethodName: "SigninAccount",
			Handler:    _Backend_SigninAccount_Handler,
		},
		{
			MethodName: "SignoutAccount",
			Handler:    _Backend_SignoutAccount_Handler,
		},
		{
			MethodName: "LockAccount",
			Handler:    _Backend_LockAccount_Handler,
		},
		{
			MethodName: "UIState",
			Handler:    _Backend_UIState_Handler,
		},
		{
			MethodName: "SaveUIState",
			Handler:    _Backend_SaveUIState_Handler,
		},
		{
			MethodName: "AccountState",
			Handler:    _Backend_AccountState_Handler,
		},
		{
			MethodName: "CreateNotebook",
			Handler:    _Backend_CreateNotebook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend.proto",
}

func init() { proto.RegisterFile("backend.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 571 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xc4, 0x55, 0x4d, 0x6f, 0x13, 0x3d,
	0x10, 0x4e, 0xf2, 0x36, 0x4d, 0x32, 0xf9, 0x78, 0x25, 0x93, 0x96, 0x90, 0x4a, 0x25, 0x58, 0x1c,
	0xca, 0x25, 0x87, 0x70, 0xe5, 0x42, 0xf9, 0x50, 0x03, 0x0d, 0x95, 0x36, 0x54, 0x1c, 0xdb, 0x4d,
	0x3c, 0x24, 0x56, 0x52, 0x7b, 0x59, 0x3b, 0xf4, 0x47, 0x20, 0xf1, 0x8b, 0x39, 0x20, 0xef, 0x3a,
	0xa9, 0xbd, 0x59, 0x52, 0x84, 0x84, 0xb8, 0xf9, 0xb1, 0x67, 0x67, 0x9e, 0x99, 0x67, 0x66, 0x16,
	0x9a, 0x93, 0x70, 0xba, 0x40, 0xc1, 0xfa, 0x51, 0x2c, 0xb5, 0x24, 0x20, 0xa4, 0xc6, 0x05, 0x62,
	0x84, 0x31, 0x7d, 0x01, 0xad, 0xb1, 0x0e, 0xf5, 0x4a, 0x05, 0xa8, 0x22, 0x29, 0x14, 0x92, 0x43,
	0xd8, 0x57, 0xc9, 0x4d, 0xa7, 0xd8, 0x2b, 0x9e, 0xd4, 0x02, 0x8b, 0x08, 0x81, 0xbd, 0xa9, 0x64,
	0xd8, 0x29, 0xf5, 0x8a, 0x27, 0xe5, 0x20, 0x39, 0xd3, 0xa7, 0xd0, 0xf8, 0x28, 0x17, 0x28, 0x02,
	0xfc, 0xb2, 0x42, 0xa5, 0x49, 0x1b, 0xca, 0xda, 0x60, 0xfb, 0x69, 0x0a, 0xe8, 0x11, 0xd4, 0x86,
	0x6c, 0x6d, 0xd2, 0x82, 0x12, 0x67, 0xf6, 0xbd, 0xc4, 0x19, 0x3d, 0x03, 0x30, 0x8f, 0x36, 0x78,
	0xe6, 0xd5, 0x21, 0x53, 0xca, 0x25, 0xf3, 0x9f, 0x43, 0xe6, 0x5b, 0x11, 0xfe, 0xbf, 0x1c, 0x9a,
	0x6c, 0x70, 0xe3, 0x6f, 0xe0, 0x25, 0x53, 0x1f, 0x74, 0xfb, 0x77, 0xb9, 0xf7, 0xfd, 0xc4, 0x37,
	0xbe, 0x7b, 0x50, 0xbf, 0xe5, 0x82, 0xc9, 0xdb, 0x4f, 0x9c, 0xe9, 0xb9, 0xcd, 0xd7, 0xbd, 0x22,
	0x14, 0x1a, 0x29, 0x3c, 0x43, 0x3e, 0x9b, 0x6b, 0xcb, 0xc2, 0xbb, 0xa3, 0xdf, 0x8b, 0x40, 0xc6,
	0xe1, 0x57, 0xdc, 0x30, 0x4a, 0xd3, 0xff, 0x77, 0x84, 0xde, 0x41, 0xfb, 0xe5, 0x74, 0x2a, 0x57,
	0x42, 0xfb, 0x25, 0xea, 0x42, 0x55, 0xf1, 0x99, 0x40, 0x36, 0x4c, 0x65, 0xab, 0x06, 0x1b, 0x6c,
	0xca, 0xbf, 0x94, 0xd3, 0x05, 0xb2, 0x24, 0x68, 0x35, 0xb0, 0x88, 0x3e, 0x83, 0x07, 0x17, 0x11,
	0x8a, 0x51, 0xa8, 0x34, 0xc6, 0xaf, 0x27, 0xeb, 0xe4, 0x08, 0xec, 0x45, 0xa1, 0x9e, 0x5b, 0xfd,
	0x92, 0x33, 0xbd, 0x86, 0xf6, 0xab, 0x18, 0x43, 0x8d, 0x36, 0xb8, 0x63, 0x2b, 0xc2, 0x1b, 0x5c,
	0xdb, 0x9a, 0xb3, 0x69, 0x1f, 0xbc, 0x09, 0xf9, 0xd2, 0x8a, 0x9d, 0x02, 0x72, 0x0c, 0x10, 0x85,
	0x4a, 0x45, 0xf3, 0x38, 0x54, 0xa9, 0xe2, 0xb5, 0xc0, 0xb9, 0xa1, 0x6f, 0xa1, 0x7d, 0x29, 0x0c,
	0xb1, 0x4c, 0x84, 0x6c, 0x2f, 0xf9, 0x7e, 0x4a, 0x5b, 0x7e, 0xae, 0xa1, 0x3d, 0xe6, 0x33, 0xc1,
	0xc5, 0x5f, 0x63, 0x7a, 0x05, 0x07, 0x69, 0x2d, 0x3e, 0x48, 0x8d, 0x13, 0x29, 0x17, 0xbb, 0x42,
	0x3c, 0x84, 0xca, 0x4a, 0x61, 0x7c, 0xc5, 0xd9, 0xba, 0xf7, 0x0d, 0x1c, 0x32, 0xf2, 0x08, 0xaa,
	0x6a, 0x8e, 0xcb, 0xcf, 0xe6, 0x25, 0x8d, 0x51, 0x49, 0xf0, 0x90, 0x0d, 0x7e, 0x94, 0xa1, 0x72,
	0x9a, 0xce, 0x3a, 0x19, 0x41, 0xc3, 0xd5, 0x88, 0x3c, 0x76, 0x3b, 0x2d, 0x47, 0xbd, 0xee, 0x8e,
	0x56, 0xa4, 0x05, 0xf2, 0x1e, 0x9a, 0x9e, 0x8e, 0xa4, 0xe7, 0x9a, 0xe7, 0x49, 0xdc, 0x3d, 0x74,
	0x2d, 0xee, 0x86, 0x9c, 0x16, 0xc8, 0x05, 0x34, 0x3d, 0xc9, 0x7c, 0x67, 0x79, 0x6a, 0xde, 0xcf,
	0xce, 0xd3, 0xce, 0x77, 0x98, 0x27, 0xeb, 0x0e, 0x76, 0x6f, 0xa0, 0x65, 0xbe, 0x90, 0x2b, 0xbd,
	0xf6, 0x76, 0x90, 0xb5, 0xfd, 0x1d, 0x4e, 0xa7, 0x50, 0x3f, 0x77, 0x52, 0xfc, 0x43, 0x1f, 0x15,
	0xbb, 0x40, 0x48, 0xc7, 0x35, 0x74, 0xb7, 0x6e, 0xf7, 0xc8, 0x2b, 0x9e, 0xbf, 0x01, 0x93, 0xda,
	0xd4, 0x9d, 0x45, 0x44, 0x8e, 0xbd, 0x80, 0x5b, 0x1b, 0xea, 0x1e, 0x42, 0xe7, 0xd0, 0x70, 0xb7,
	0xc8, 0x0e, 0x56, 0x9e, 0x02, 0x79, 0x9b, 0x87, 0x16, 0xc8, 0x08, 0x5a, 0xfe, 0x40, 0x90, 0x27,
	0xdb, 0x5d, 0x95, 0x19, 0x96, 0x5f, 0x0b, 0x37, 0xd9, 0x4f, 0xfe, 0x6f, 0xcf, 0x7f, 0x06, 0x00,
	0x00, 0xff, 0xff, 0xb8, 0x0f, 0x85, 0x78, 0xf0, 0x06, 0x00, 0x00,
}
