// Code generated by protoc-gen-go.
// source: common.proto
// DO NOT EDIT!

package notekeeper

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// All requests will include this embedded message type
type RequestHeader struct {
	Method    string `protobuf:"bytes,1,opt,name=method" json:"method,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Sequence  int32  `protobuf:"varint,3,opt,name=sequence" json:"sequence,omitempty"`
}

func (m *RequestHeader) Reset()                    { *m = RequestHeader{} }
func (m *RequestHeader) String() string            { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()               {}
func (*RequestHeader) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *RequestHeader) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *RequestHeader) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *RequestHeader) GetSequence() int32 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

// All responses will include this embedded message type
type ResponseHeader struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Code   int32  `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
}

func (m *ResponseHeader) Reset()                    { *m = ResponseHeader{} }
func (m *ResponseHeader) String() string            { return proto.CompactTextString(m) }
func (*ResponseHeader) ProtoMessage()               {}
func (*ResponseHeader) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *ResponseHeader) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ResponseHeader) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestHeader)(nil), "notekeeper.RequestHeader")
	proto.RegisterType((*ResponseHeader)(nil), "notekeeper.ResponseHeader")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8e, 0x31, 0x0e, 0x82, 0x40,
	0x10, 0x45, 0xb3, 0x2a, 0x44, 0x26, 0x68, 0xb1, 0x85, 0x21, 0xc6, 0x82, 0x50, 0x51, 0xd9, 0xd8,
	0x7a, 0x00, 0xeb, 0xbd, 0xc1, 0x0a, 0x3f, 0x6a, 0x0c, 0x3b, 0xb8, 0x33, 0xdc, 0xdf, 0x08, 0x2a,
	0xdd, 0xbc, 0x29, 0xde, 0xfb, 0x94, 0x37, 0xdc, 0x75, 0x1c, 0x8e, 0x7d, 0x64, 0x65, 0x4b, 0x81,
	0x15, 0x4f, 0xa0, 0x47, 0xac, 0x3c, 0x6d, 0x1c, 0x5e, 0x03, 0x44, 0x2f, 0xf0, 0x2d, 0xa2, 0xdd,
	0x51, 0xda, 0x41, 0xef, 0xdc, 0x16, 0xa6, 0x34, 0x75, 0xe6, 0xbe, 0x64, 0x0f, 0x94, 0xc9, 0xe3,
	0x16, 0xbc, 0x0e, 0x11, 0xc5, 0xa2, 0x34, 0x75, 0xee, 0xe6, 0x87, 0xdd, 0xd3, 0x5a, 0x3e, 0x9a,
	0xd0, 0xa0, 0x58, 0x96, 0xa6, 0x4e, 0xdc, 0x9f, 0xab, 0x33, 0x6d, 0x1d, 0xa4, 0xe7, 0x20, 0x98,
	0x1b, 0xa2, 0x5e, 0x07, 0xf9, 0x35, 0x26, 0xb2, 0x96, 0x56, 0x0d, 0xb7, 0x93, 0x3e, 0x71, 0xe3,
	0x7d, 0x4d, 0xc7, 0xcd, 0xa7, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x11, 0x2d, 0x68, 0xc3,
	0x00, 0x00, 0x00,
}
