// Code generated by protoc-gen-go. DO NOT EDIT.
// source: collection.proto

package notekeeper

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Collection struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 *Title   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Locked               bool     `protobuf:"varint,3,opt,name=locked,proto3" json:"locked,omitempty"`
	ShelfId              string   `protobuf:"bytes,4,opt,name=shelfId,proto3" json:"shelfId,omitempty"`
	Created              string   `protobuf:"bytes,5,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string   `protobuf:"bytes,6,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Collection) Reset()         { *m = Collection{} }
func (m *Collection) String() string { return proto.CompactTextString(m) }
func (*Collection) ProtoMessage()    {}
func (*Collection) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eceb2b1ad103104, []int{0}
}

func (m *Collection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Collection.Unmarshal(m, b)
}
func (m *Collection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Collection.Marshal(b, m, deterministic)
}
func (m *Collection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Collection.Merge(m, src)
}
func (m *Collection) XXX_Size() int {
	return xxx_messageInfo_Collection.Size(m)
}
func (m *Collection) XXX_DiscardUnknown() {
	xxx_messageInfo_Collection.DiscardUnknown(m)
}

var xxx_messageInfo_Collection proto.InternalMessageInfo

func (m *Collection) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Collection) GetName() *Title {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Collection) GetLocked() bool {
	if m != nil {
		return m.Locked
	}
	return false
}

func (m *Collection) GetShelfId() string {
	if m != nil {
		return m.ShelfId
	}
	return ""
}

func (m *Collection) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Collection) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

type GetCollectionsRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	ShelfId              string         `protobuf:"bytes,2,opt,name=shelfId,proto3" json:"shelfId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetCollectionsRequest) Reset()         { *m = GetCollectionsRequest{} }
func (m *GetCollectionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetCollectionsRequest) ProtoMessage()    {}
func (*GetCollectionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eceb2b1ad103104, []int{1}
}

func (m *GetCollectionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCollectionsRequest.Unmarshal(m, b)
}
func (m *GetCollectionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCollectionsRequest.Marshal(b, m, deterministic)
}
func (m *GetCollectionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCollectionsRequest.Merge(m, src)
}
func (m *GetCollectionsRequest) XXX_Size() int {
	return xxx_messageInfo_GetCollectionsRequest.Size(m)
}
func (m *GetCollectionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCollectionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCollectionsRequest proto.InternalMessageInfo

func (m *GetCollectionsRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetCollectionsRequest) GetShelfId() string {
	if m != nil {
		return m.ShelfId
	}
	return ""
}

type GetCollectionsResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Collections          []*Collection   `protobuf:"bytes,2,rep,name=collections,proto3" json:"collections,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetCollectionsResponse) Reset()         { *m = GetCollectionsResponse{} }
func (m *GetCollectionsResponse) String() string { return proto.CompactTextString(m) }
func (*GetCollectionsResponse) ProtoMessage()    {}
func (*GetCollectionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eceb2b1ad103104, []int{2}
}

func (m *GetCollectionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCollectionsResponse.Unmarshal(m, b)
}
func (m *GetCollectionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCollectionsResponse.Marshal(b, m, deterministic)
}
func (m *GetCollectionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCollectionsResponse.Merge(m, src)
}
func (m *GetCollectionsResponse) XXX_Size() int {
	return xxx_messageInfo_GetCollectionsResponse.Size(m)
}
func (m *GetCollectionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCollectionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCollectionsResponse proto.InternalMessageInfo

func (m *GetCollectionsResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetCollectionsResponse) GetCollections() []*Collection {
	if m != nil {
		return m.Collections
	}
	return nil
}

type CreateCollectionRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Name                 *Title         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ShelfId              string         `protobuf:"bytes,3,opt,name=shelfId,proto3" json:"shelfId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateCollectionRequest) Reset()         { *m = CreateCollectionRequest{} }
func (m *CreateCollectionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCollectionRequest) ProtoMessage()    {}
func (*CreateCollectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eceb2b1ad103104, []int{3}
}

func (m *CreateCollectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCollectionRequest.Unmarshal(m, b)
}
func (m *CreateCollectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCollectionRequest.Marshal(b, m, deterministic)
}
func (m *CreateCollectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCollectionRequest.Merge(m, src)
}
func (m *CreateCollectionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCollectionRequest.Size(m)
}
func (m *CreateCollectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCollectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCollectionRequest proto.InternalMessageInfo

func (m *CreateCollectionRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *CreateCollectionRequest) GetName() *Title {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *CreateCollectionRequest) GetShelfId() string {
	if m != nil {
		return m.ShelfId
	}
	return ""
}

type SaveCollectionRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Id                   string         `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	ShelfId              string         `protobuf:"bytes,3,opt,name=shelfId,proto3" json:"shelfId,omitempty"`
	Name                 *Title         `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Locked               bool           `protobuf:"varint,5,opt,name=locked,proto3" json:"locked,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SaveCollectionRequest) Reset()         { *m = SaveCollectionRequest{} }
func (m *SaveCollectionRequest) String() string { return proto.CompactTextString(m) }
func (*SaveCollectionRequest) ProtoMessage()    {}
func (*SaveCollectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eceb2b1ad103104, []int{4}
}

func (m *SaveCollectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveCollectionRequest.Unmarshal(m, b)
}
func (m *SaveCollectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveCollectionRequest.Marshal(b, m, deterministic)
}
func (m *SaveCollectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveCollectionRequest.Merge(m, src)
}
func (m *SaveCollectionRequest) XXX_Size() int {
	return xxx_messageInfo_SaveCollectionRequest.Size(m)
}
func (m *SaveCollectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveCollectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveCollectionRequest proto.InternalMessageInfo

func (m *SaveCollectionRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SaveCollectionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SaveCollectionRequest) GetShelfId() string {
	if m != nil {
		return m.ShelfId
	}
	return ""
}

func (m *SaveCollectionRequest) GetName() *Title {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *SaveCollectionRequest) GetLocked() bool {
	if m != nil {
		return m.Locked
	}
	return false
}

type DeleteCollectionRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Id                   string         `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	ShelfId              string         `protobuf:"bytes,3,opt,name=shelfId,proto3" json:"shelfId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DeleteCollectionRequest) Reset()         { *m = DeleteCollectionRequest{} }
func (m *DeleteCollectionRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCollectionRequest) ProtoMessage()    {}
func (*DeleteCollectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eceb2b1ad103104, []int{5}
}

func (m *DeleteCollectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCollectionRequest.Unmarshal(m, b)
}
func (m *DeleteCollectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCollectionRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCollectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCollectionRequest.Merge(m, src)
}
func (m *DeleteCollectionRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCollectionRequest.Size(m)
}
func (m *DeleteCollectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCollectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCollectionRequest proto.InternalMessageInfo

func (m *DeleteCollectionRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *DeleteCollectionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteCollectionRequest) GetShelfId() string {
	if m != nil {
		return m.ShelfId
	}
	return ""
}

func init() {
	proto.RegisterType((*Collection)(nil), "notekeeper.Collection")
	proto.RegisterType((*GetCollectionsRequest)(nil), "notekeeper.GetCollectionsRequest")
	proto.RegisterType((*GetCollectionsResponse)(nil), "notekeeper.GetCollectionsResponse")
	proto.RegisterType((*CreateCollectionRequest)(nil), "notekeeper.CreateCollectionRequest")
	proto.RegisterType((*SaveCollectionRequest)(nil), "notekeeper.SaveCollectionRequest")
	proto.RegisterType((*DeleteCollectionRequest)(nil), "notekeeper.DeleteCollectionRequest")
}

func init() { proto.RegisterFile("collection.proto", fileDescriptor_9eceb2b1ad103104) }

var fileDescriptor_9eceb2b1ad103104 = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0x41, 0x4b, 0xf3, 0x40,
	0x14, 0xfc, 0x36, 0x6d, 0xf3, 0xe9, 0x8b, 0x88, 0x2e, 0xb4, 0x5d, 0x7b, 0x0a, 0x01, 0x21, 0xa7,
	0x82, 0xf1, 0xe2, 0xbd, 0x82, 0x7a, 0x2b, 0xab, 0x7f, 0x20, 0x66, 0x9f, 0x34, 0x74, 0x9b, 0x8d,
	0xd9, 0x6d, 0x7f, 0x82, 0x37, 0x7f, 0x88, 0x67, 0xff, 0xa0, 0x74, 0x93, 0x36, 0xdb, 0x82, 0x50,
	0x44, 0x3c, 0x0e, 0x33, 0xfb, 0x66, 0xf2, 0xde, 0x04, 0xce, 0x32, 0x25, 0x25, 0x66, 0x26, 0x57,
	0xc5, 0xb8, 0xac, 0x94, 0x51, 0x14, 0x0a, 0x65, 0x70, 0x8e, 0x58, 0x62, 0x35, 0x3a, 0xc9, 0xd4,
	0x62, 0xb1, 0x61, 0x46, 0x81, 0xc9, 0x8d, 0xc4, 0x1a, 0x44, 0x1f, 0x04, 0x60, 0xb2, 0x7d, 0x4b,
	0x4f, 0xc1, 0xcb, 0x05, 0x23, 0x21, 0x89, 0x8f, 0xb9, 0x97, 0x0b, 0x7a, 0x09, 0xdd, 0x22, 0x5d,
	0x20, 0xf3, 0x42, 0x12, 0x07, 0xc9, 0xf9, 0xb8, 0x1d, 0x3a, 0x7e, 0x5a, 0x4f, 0xe1, 0x96, 0xa6,
	0x03, 0xf0, 0xa5, 0xca, 0xe6, 0x28, 0x58, 0x27, 0x24, 0xf1, 0x11, 0x6f, 0x10, 0x65, 0xf0, 0x5f,
	0xcf, 0x50, 0xbe, 0x3c, 0x08, 0xd6, 0xb5, 0x33, 0x37, 0x70, 0xcd, 0x64, 0x15, 0xa6, 0x06, 0x05,
	0xeb, 0xd5, 0x4c, 0x03, 0xd7, 0xcc, 0xb2, 0x14, 0x96, 0xf1, 0x6b, 0xa6, 0x81, 0x91, 0x80, 0xfe,
	0x1d, 0x9a, 0x36, 0xad, 0xe6, 0xf8, 0xba, 0x44, 0x6d, 0xe8, 0x15, 0xf8, 0x33, 0x4c, 0x05, 0x56,
	0x36, 0x79, 0x90, 0x5c, 0xb8, 0x39, 0x1b, 0xd1, 0xbd, 0x15, 0xf0, 0x46, 0xe8, 0x26, 0xf3, 0x76,
	0x92, 0x45, 0x6f, 0x04, 0x06, 0xfb, 0x36, 0xba, 0x54, 0x85, 0x46, 0x9a, 0xec, 0xf9, 0x8c, 0x76,
	0x7d, 0x6a, 0xd5, 0x9e, 0xd1, 0x0d, 0x04, 0xed, 0x6d, 0x34, 0xf3, 0xc2, 0x4e, 0x1c, 0x24, 0x03,
	0xf7, 0x61, 0xeb, 0xc4, 0x5d, 0x69, 0xf4, 0x4e, 0x60, 0x38, 0xb1, 0x4b, 0x71, 0x14, 0x3f, 0xff,
	0xe2, 0x03, 0x4f, 0xe9, 0x2c, 0xa6, 0xb3, 0xbb, 0x98, 0x4f, 0x02, 0xfd, 0xc7, 0x74, 0xf5, 0x3b,
	0x69, 0xea, 0xa2, 0x79, 0xdb, 0xa2, 0x7d, 0x6b, 0xbb, 0xcd, 0xdd, 0x3d, 0xb4, 0x82, 0x3d, 0xb7,
	0x82, 0xd1, 0x0a, 0x86, 0xb7, 0x28, 0xd1, 0xfc, 0x71, 0xec, 0xe9, 0xbf, 0x29, 0x79, 0xf6, 0xed,
	0x3f, 0x76, 0xfd, 0x15, 0x00, 0x00, 0xff, 0xff, 0xa4, 0x62, 0x2a, 0x6a, 0x9e, 0x03, 0x00, 0x00,
}
