// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kex.proto

package notekeeper

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// A key exchange client request
type KeyExchangeRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	PublicKey            []byte         `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *KeyExchangeRequest) Reset()         { *m = KeyExchangeRequest{} }
func (m *KeyExchangeRequest) String() string { return proto.CompactTextString(m) }
func (*KeyExchangeRequest) ProtoMessage()    {}
func (*KeyExchangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d370dc43d05af896, []int{0}
}

func (m *KeyExchangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyExchangeRequest.Unmarshal(m, b)
}
func (m *KeyExchangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyExchangeRequest.Marshal(b, m, deterministic)
}
func (m *KeyExchangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyExchangeRequest.Merge(m, src)
}
func (m *KeyExchangeRequest) XXX_Size() int {
	return xxx_messageInfo_KeyExchangeRequest.Size(m)
}
func (m *KeyExchangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyExchangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeyExchangeRequest proto.InternalMessageInfo

func (m *KeyExchangeRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *KeyExchangeRequest) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

// A key exchange server response
type KeyExchangeResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	PublicKey            []byte          `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *KeyExchangeResponse) Reset()         { *m = KeyExchangeResponse{} }
func (m *KeyExchangeResponse) String() string { return proto.CompactTextString(m) }
func (*KeyExchangeResponse) ProtoMessage()    {}
func (*KeyExchangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d370dc43d05af896, []int{1}
}

func (m *KeyExchangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyExchangeResponse.Unmarshal(m, b)
}
func (m *KeyExchangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyExchangeResponse.Marshal(b, m, deterministic)
}
func (m *KeyExchangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyExchangeResponse.Merge(m, src)
}
func (m *KeyExchangeResponse) XXX_Size() int {
	return xxx_messageInfo_KeyExchangeResponse.Size(m)
}
func (m *KeyExchangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyExchangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KeyExchangeResponse proto.InternalMessageInfo

func (m *KeyExchangeResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *KeyExchangeResponse) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func init() {
	proto.RegisterType((*KeyExchangeRequest)(nil), "notekeeper.KeyExchangeRequest")
	proto.RegisterType((*KeyExchangeResponse)(nil), "notekeeper.KeyExchangeResponse")
}

func init() { proto.RegisterFile("kex.proto", fileDescriptor_d370dc43d05af896) }

var fileDescriptor_d370dc43d05af896 = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x4e, 0xad, 0xd0,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xca, 0xcb, 0x2f, 0x49, 0xcd, 0x4e, 0x4d, 0x2d, 0x48,
	0x2d, 0x92, 0xe2, 0x49, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0x83, 0xc8, 0x28, 0xa5, 0x72, 0x09, 0x79,
	0xa7, 0x56, 0xba, 0x56, 0x24, 0x67, 0x24, 0xe6, 0xa5, 0xa7, 0x06, 0xa5, 0x16, 0x96, 0xa6, 0x16,
	0x97, 0x08, 0x19, 0x72, 0xb1, 0x65, 0xa4, 0x26, 0xa6, 0xa4, 0x16, 0x49, 0x30, 0x2a, 0x30, 0x6a,
	0x70, 0x1b, 0x49, 0xea, 0x21, 0x0c, 0xd0, 0x83, 0x2a, 0xf2, 0x00, 0x2b, 0x08, 0x82, 0x2a, 0x14,
	0x92, 0xe1, 0xe2, 0x2c, 0x28, 0x4d, 0xca, 0xc9, 0x4c, 0xf6, 0x4e, 0xad, 0x94, 0x60, 0x52, 0x60,
	0xd4, 0xe0, 0x09, 0x42, 0x08, 0x28, 0xa5, 0x73, 0x09, 0xa3, 0x58, 0x53, 0x5c, 0x90, 0x9f, 0x57,
	0x9c, 0x2a, 0x64, 0x84, 0x66, 0x8f, 0x14, 0xaa, 0x3d, 0x10, 0x55, 0xa4, 0x58, 0x94, 0xc4, 0x06,
	0xf6, 0x96, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xf1, 0x84, 0x1f, 0x78, 0xfd, 0x00, 0x00, 0x00,
}
