// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notebook.proto

package notekeeper

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Notebook struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 *Title   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Container            string   `protobuf:"bytes,3,opt,name=container,proto3" json:"container,omitempty"`
	OwnerId              string   `protobuf:"bytes,4,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	ContainerId          string   `protobuf:"bytes,5,opt,name=containerId,proto3" json:"containerId,omitempty"`
	Default              bool     `protobuf:"varint,6,opt,name=default,proto3" json:"default,omitempty"`
	Locked               bool     `protobuf:"varint,7,opt,name=locked,proto3" json:"locked,omitempty"`
	NoteCount            int32    `protobuf:"varint,8,opt,name=noteCount,proto3" json:"noteCount,omitempty"`
	Created              string   `protobuf:"bytes,9,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string   `protobuf:"bytes,10,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Notebook) Reset()         { *m = Notebook{} }
func (m *Notebook) String() string { return proto.CompactTextString(m) }
func (*Notebook) ProtoMessage()    {}
func (*Notebook) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4288154b4c2ba34, []int{0}
}

func (m *Notebook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notebook.Unmarshal(m, b)
}
func (m *Notebook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notebook.Marshal(b, m, deterministic)
}
func (m *Notebook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notebook.Merge(m, src)
}
func (m *Notebook) XXX_Size() int {
	return xxx_messageInfo_Notebook.Size(m)
}
func (m *Notebook) XXX_DiscardUnknown() {
	xxx_messageInfo_Notebook.DiscardUnknown(m)
}

var xxx_messageInfo_Notebook proto.InternalMessageInfo

func (m *Notebook) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Notebook) GetName() *Title {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Notebook) GetContainer() string {
	if m != nil {
		return m.Container
	}
	return ""
}

func (m *Notebook) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func (m *Notebook) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *Notebook) GetDefault() bool {
	if m != nil {
		return m.Default
	}
	return false
}

func (m *Notebook) GetLocked() bool {
	if m != nil {
		return m.Locked
	}
	return false
}

func (m *Notebook) GetNoteCount() int32 {
	if m != nil {
		return m.NoteCount
	}
	return 0
}

func (m *Notebook) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Notebook) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

type CreateNotebookRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Name                 *Title         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Container            string         `protobuf:"bytes,3,opt,name=container,proto3" json:"container,omitempty"`
	OwnerId              string         `protobuf:"bytes,4,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	ContainerId          string         `protobuf:"bytes,5,opt,name=containerId,proto3" json:"containerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateNotebookRequest) Reset()         { *m = CreateNotebookRequest{} }
func (m *CreateNotebookRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNotebookRequest) ProtoMessage()    {}
func (*CreateNotebookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4288154b4c2ba34, []int{1}
}

func (m *CreateNotebookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNotebookRequest.Unmarshal(m, b)
}
func (m *CreateNotebookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNotebookRequest.Marshal(b, m, deterministic)
}
func (m *CreateNotebookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNotebookRequest.Merge(m, src)
}
func (m *CreateNotebookRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNotebookRequest.Size(m)
}
func (m *CreateNotebookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNotebookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNotebookRequest proto.InternalMessageInfo

func (m *CreateNotebookRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *CreateNotebookRequest) GetName() *Title {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *CreateNotebookRequest) GetContainer() string {
	if m != nil {
		return m.Container
	}
	return ""
}

func (m *CreateNotebookRequest) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func (m *CreateNotebookRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

type SaveNotebookRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Id                   string         `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name                 *Title         `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Container            string         `protobuf:"bytes,4,opt,name=container,proto3" json:"container,omitempty"`
	OwnerId              string         `protobuf:"bytes,5,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	ContainerId          string         `protobuf:"bytes,6,opt,name=containerId,proto3" json:"containerId,omitempty"`
	Default              bool           `protobuf:"varint,7,opt,name=default,proto3" json:"default,omitempty"`
	Locked               bool           `protobuf:"varint,8,opt,name=locked,proto3" json:"locked,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SaveNotebookRequest) Reset()         { *m = SaveNotebookRequest{} }
func (m *SaveNotebookRequest) String() string { return proto.CompactTextString(m) }
func (*SaveNotebookRequest) ProtoMessage()    {}
func (*SaveNotebookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4288154b4c2ba34, []int{2}
}

func (m *SaveNotebookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveNotebookRequest.Unmarshal(m, b)
}
func (m *SaveNotebookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveNotebookRequest.Marshal(b, m, deterministic)
}
func (m *SaveNotebookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveNotebookRequest.Merge(m, src)
}
func (m *SaveNotebookRequest) XXX_Size() int {
	return xxx_messageInfo_SaveNotebookRequest.Size(m)
}
func (m *SaveNotebookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveNotebookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveNotebookRequest proto.InternalMessageInfo

func (m *SaveNotebookRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SaveNotebookRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SaveNotebookRequest) GetName() *Title {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *SaveNotebookRequest) GetContainer() string {
	if m != nil {
		return m.Container
	}
	return ""
}

func (m *SaveNotebookRequest) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func (m *SaveNotebookRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *SaveNotebookRequest) GetDefault() bool {
	if m != nil {
		return m.Default
	}
	return false
}

func (m *SaveNotebookRequest) GetLocked() bool {
	if m != nil {
		return m.Locked
	}
	return false
}

type GetNotebooksRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Container            string         `protobuf:"bytes,2,opt,name=container,proto3" json:"container,omitempty"`
	OwnerId              string         `protobuf:"bytes,3,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	ContainerId          string         `protobuf:"bytes,4,opt,name=containerId,proto3" json:"containerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetNotebooksRequest) Reset()         { *m = GetNotebooksRequest{} }
func (m *GetNotebooksRequest) String() string { return proto.CompactTextString(m) }
func (*GetNotebooksRequest) ProtoMessage()    {}
func (*GetNotebooksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4288154b4c2ba34, []int{3}
}

func (m *GetNotebooksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNotebooksRequest.Unmarshal(m, b)
}
func (m *GetNotebooksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNotebooksRequest.Marshal(b, m, deterministic)
}
func (m *GetNotebooksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNotebooksRequest.Merge(m, src)
}
func (m *GetNotebooksRequest) XXX_Size() int {
	return xxx_messageInfo_GetNotebooksRequest.Size(m)
}
func (m *GetNotebooksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNotebooksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNotebooksRequest proto.InternalMessageInfo

func (m *GetNotebooksRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetNotebooksRequest) GetContainer() string {
	if m != nil {
		return m.Container
	}
	return ""
}

func (m *GetNotebooksRequest) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func (m *GetNotebooksRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

type GetNotebooksResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Notebooks            []*Notebook     `protobuf:"bytes,2,rep,name=notebooks,proto3" json:"notebooks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetNotebooksResponse) Reset()         { *m = GetNotebooksResponse{} }
func (m *GetNotebooksResponse) String() string { return proto.CompactTextString(m) }
func (*GetNotebooksResponse) ProtoMessage()    {}
func (*GetNotebooksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4288154b4c2ba34, []int{4}
}

func (m *GetNotebooksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNotebooksResponse.Unmarshal(m, b)
}
func (m *GetNotebooksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNotebooksResponse.Marshal(b, m, deterministic)
}
func (m *GetNotebooksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNotebooksResponse.Merge(m, src)
}
func (m *GetNotebooksResponse) XXX_Size() int {
	return xxx_messageInfo_GetNotebooksResponse.Size(m)
}
func (m *GetNotebooksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNotebooksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNotebooksResponse proto.InternalMessageInfo

func (m *GetNotebooksResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetNotebooksResponse) GetNotebooks() []*Notebook {
	if m != nil {
		return m.Notebooks
	}
	return nil
}

type DeleteNotebookRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Id                   string         `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Container            string         `protobuf:"bytes,3,opt,name=container,proto3" json:"container,omitempty"`
	OwnerId              string         `protobuf:"bytes,4,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	ContainerId          string         `protobuf:"bytes,5,opt,name=containerId,proto3" json:"containerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DeleteNotebookRequest) Reset()         { *m = DeleteNotebookRequest{} }
func (m *DeleteNotebookRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteNotebookRequest) ProtoMessage()    {}
func (*DeleteNotebookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4288154b4c2ba34, []int{5}
}

func (m *DeleteNotebookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNotebookRequest.Unmarshal(m, b)
}
func (m *DeleteNotebookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNotebookRequest.Marshal(b, m, deterministic)
}
func (m *DeleteNotebookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNotebookRequest.Merge(m, src)
}
func (m *DeleteNotebookRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteNotebookRequest.Size(m)
}
func (m *DeleteNotebookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNotebookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNotebookRequest proto.InternalMessageInfo

func (m *DeleteNotebookRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *DeleteNotebookRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteNotebookRequest) GetContainer() string {
	if m != nil {
		return m.Container
	}
	return ""
}

func (m *DeleteNotebookRequest) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func (m *DeleteNotebookRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func init() {
	proto.RegisterType((*Notebook)(nil), "notekeeper.Notebook")
	proto.RegisterType((*CreateNotebookRequest)(nil), "notekeeper.CreateNotebookRequest")
	proto.RegisterType((*SaveNotebookRequest)(nil), "notekeeper.SaveNotebookRequest")
	proto.RegisterType((*GetNotebooksRequest)(nil), "notekeeper.GetNotebooksRequest")
	proto.RegisterType((*GetNotebooksResponse)(nil), "notekeeper.GetNotebooksResponse")
	proto.RegisterType((*DeleteNotebookRequest)(nil), "notekeeper.DeleteNotebookRequest")
}

func init() { proto.RegisterFile("notebook.proto", fileDescriptor_e4288154b4c2ba34) }

var fileDescriptor_e4288154b4c2ba34 = []byte{
	// 408 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0x51, 0xaa, 0xd3, 0x40,
	0x14, 0x75, 0x26, 0x69, 0x9a, 0xde, 0xc8, 0x03, 0xe7, 0xbd, 0x27, 0x63, 0xf1, 0x23, 0x04, 0x84,
	0x7c, 0x15, 0x8c, 0x4b, 0xa8, 0xa0, 0xfd, 0x91, 0x12, 0xdd, 0x40, 0x9a, 0xb9, 0x62, 0x68, 0x3a,
	0x13, 0x93, 0x89, 0xfe, 0xb9, 0x01, 0x17, 0x21, 0xb8, 0x06, 0x77, 0xe1, 0xa6, 0x24, 0x93, 0xa4,
	0x49, 0x5b, 0x0c, 0x88, 0x16, 0x3f, 0xcf, 0x9c, 0x73, 0x2f, 0xe7, 0xdc, 0x9e, 0x06, 0x6e, 0xa4,
	0xd2, 0xb8, 0x53, 0x6a, 0xbf, 0x2a, 0x4a, 0xa5, 0x15, 0x83, 0x06, 0xef, 0x11, 0x0b, 0x2c, 0x97,
	0x0f, 0x53, 0x75, 0x38, 0x28, 0xd9, 0x32, 0x4b, 0x4f, 0x67, 0x3a, 0xc7, 0x16, 0x04, 0xdf, 0x28,
	0xb8, 0x6f, 0xba, 0x49, 0x76, 0x03, 0x34, 0x13, 0x9c, 0xf8, 0x24, 0x5c, 0xc4, 0x34, 0x13, 0xec,
	0x19, 0xd8, 0x32, 0x39, 0x20, 0xa7, 0x3e, 0x09, 0xbd, 0xe8, 0xd1, 0x6a, 0x58, 0xb9, 0x7a, 0xd7,
	0xec, 0x88, 0x0d, 0xcd, 0x9e, 0xc2, 0x22, 0x55, 0x52, 0x27, 0x99, 0xc4, 0x92, 0x5b, 0x66, 0x7a,
	0x78, 0x60, 0x1c, 0xe6, 0xea, 0xb3, 0xc4, 0x72, 0x23, 0xb8, 0x6d, 0xb8, 0x1e, 0x32, 0x1f, 0xbc,
	0xa3, 0x6c, 0x23, 0xf8, 0xcc, 0xb0, 0xe3, 0xa7, 0x66, 0x56, 0xe0, 0xfb, 0xa4, 0xce, 0x35, 0x77,
	0x7c, 0x12, 0xba, 0x71, 0x0f, 0xd9, 0x63, 0x70, 0x72, 0x95, 0xee, 0x51, 0xf0, 0xb9, 0x21, 0x3a,
	0xd4, 0x78, 0x69, 0x5c, 0xae, 0x55, 0x2d, 0x35, 0x77, 0x7d, 0x12, 0xce, 0xe2, 0xe1, 0xa1, 0xd9,
	0x97, 0x96, 0x98, 0x68, 0x14, 0x7c, 0xd1, 0x7a, 0xe9, 0x60, 0xc3, 0xd4, 0x85, 0x30, 0x0c, 0xb4,
	0x4c, 0x07, 0x83, 0x9f, 0x04, 0xee, 0xd7, 0x46, 0xd5, 0xdf, 0x29, 0xc6, 0x8f, 0x35, 0x56, 0x9a,
	0x3d, 0x07, 0xe7, 0x03, 0x26, 0x02, 0x4b, 0x73, 0x32, 0x2f, 0x7a, 0x32, 0x3e, 0x50, 0x27, 0x7a,
	0x6d, 0x04, 0x71, 0x27, 0xfc, 0xef, 0x17, 0x0d, 0xbe, 0x52, 0xb8, 0x7d, 0x9b, 0x7c, 0xfa, 0x17,
	0x59, 0xda, 0xb6, 0xd0, 0x8b, 0xb6, 0x58, 0x7f, 0x90, 0xcd, 0x9e, 0xc8, 0x36, 0x9b, 0xcc, 0xe6,
	0x4c, 0xb6, 0x65, 0xfe, 0xbb, 0xb6, 0xb8, 0xe3, 0xb6, 0x04, 0xdf, 0x09, 0xdc, 0xbe, 0x42, 0xdd,
	0x1f, 0xa3, 0xfa, 0x8b, 0x6b, 0x9c, 0xc4, 0xa2, 0x13, 0xb1, 0xac, 0xc9, 0x58, 0xf6, 0xe5, 0x4f,
	0xf6, 0x05, 0xee, 0x4e, 0x3d, 0x56, 0x85, 0x92, 0x15, 0xb2, 0xe8, 0xcc, 0xe4, 0xf2, 0xd4, 0x64,
	0xab, 0x3a, 0x73, 0x19, 0xb5, 0x7f, 0x0f, 0xb3, 0x88, 0x53, 0xdf, 0x0a, 0xbd, 0xe8, 0x6e, 0x3c,
	0x76, 0xac, 0xc5, 0x20, 0x0b, 0x7e, 0x10, 0xb8, 0x7f, 0x89, 0x39, 0xea, 0x6b, 0x94, 0xe6, 0x6a,
	0x4d, 0xdf, 0x3e, 0xd8, 0x92, 0x9d, 0x63, 0x3e, 0x72, 0x2f, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff,
	0x37, 0xf2, 0xe1, 0x12, 0x1d, 0x05, 0x00, 0x00,
}
