// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shelf.proto

package notekeeper

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Shelf struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 *Title   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Default              bool     `protobuf:"varint,4,opt,name=default,proto3" json:"default,omitempty"`
	Trash                bool     `protobuf:"varint,5,opt,name=trash,proto3" json:"trash,omitempty"`
	Locked               bool     `protobuf:"varint,6,opt,name=locked,proto3" json:"locked,omitempty"`
	Created              string   `protobuf:"bytes,7,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string   `protobuf:"bytes,8,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Shelf) Reset()         { *m = Shelf{} }
func (m *Shelf) String() string { return proto.CompactTextString(m) }
func (*Shelf) ProtoMessage()    {}
func (*Shelf) Descriptor() ([]byte, []int) {
	return fileDescriptor_997c08397bcb74ab, []int{0}
}

func (m *Shelf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Shelf.Unmarshal(m, b)
}
func (m *Shelf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Shelf.Marshal(b, m, deterministic)
}
func (m *Shelf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Shelf.Merge(m, src)
}
func (m *Shelf) XXX_Size() int {
	return xxx_messageInfo_Shelf.Size(m)
}
func (m *Shelf) XXX_DiscardUnknown() {
	xxx_messageInfo_Shelf.DiscardUnknown(m)
}

var xxx_messageInfo_Shelf proto.InternalMessageInfo

func (m *Shelf) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Shelf) GetName() *Title {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Shelf) GetDefault() bool {
	if m != nil {
		return m.Default
	}
	return false
}

func (m *Shelf) GetTrash() bool {
	if m != nil {
		return m.Trash
	}
	return false
}

func (m *Shelf) GetLocked() bool {
	if m != nil {
		return m.Locked
	}
	return false
}

func (m *Shelf) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Shelf) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

type GetShelvesRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Id                   string         `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetShelvesRequest) Reset()         { *m = GetShelvesRequest{} }
func (m *GetShelvesRequest) String() string { return proto.CompactTextString(m) }
func (*GetShelvesRequest) ProtoMessage()    {}
func (*GetShelvesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_997c08397bcb74ab, []int{1}
}

func (m *GetShelvesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShelvesRequest.Unmarshal(m, b)
}
func (m *GetShelvesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShelvesRequest.Marshal(b, m, deterministic)
}
func (m *GetShelvesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShelvesRequest.Merge(m, src)
}
func (m *GetShelvesRequest) XXX_Size() int {
	return xxx_messageInfo_GetShelvesRequest.Size(m)
}
func (m *GetShelvesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShelvesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetShelvesRequest proto.InternalMessageInfo

func (m *GetShelvesRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetShelvesRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetShelvesResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Shelves              []*Shelf        `protobuf:"bytes,2,rep,name=shelves,proto3" json:"shelves,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetShelvesResponse) Reset()         { *m = GetShelvesResponse{} }
func (m *GetShelvesResponse) String() string { return proto.CompactTextString(m) }
func (*GetShelvesResponse) ProtoMessage()    {}
func (*GetShelvesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_997c08397bcb74ab, []int{2}
}

func (m *GetShelvesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShelvesResponse.Unmarshal(m, b)
}
func (m *GetShelvesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShelvesResponse.Marshal(b, m, deterministic)
}
func (m *GetShelvesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShelvesResponse.Merge(m, src)
}
func (m *GetShelvesResponse) XXX_Size() int {
	return xxx_messageInfo_GetShelvesResponse.Size(m)
}
func (m *GetShelvesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShelvesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetShelvesResponse proto.InternalMessageInfo

func (m *GetShelvesResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetShelvesResponse) GetShelves() []*Shelf {
	if m != nil {
		return m.Shelves
	}
	return nil
}

type CreateShelfRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Name                 *Title         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string         `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateShelfRequest) Reset()         { *m = CreateShelfRequest{} }
func (m *CreateShelfRequest) String() string { return proto.CompactTextString(m) }
func (*CreateShelfRequest) ProtoMessage()    {}
func (*CreateShelfRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_997c08397bcb74ab, []int{3}
}

func (m *CreateShelfRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateShelfRequest.Unmarshal(m, b)
}
func (m *CreateShelfRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateShelfRequest.Marshal(b, m, deterministic)
}
func (m *CreateShelfRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateShelfRequest.Merge(m, src)
}
func (m *CreateShelfRequest) XXX_Size() int {
	return xxx_messageInfo_CreateShelfRequest.Size(m)
}
func (m *CreateShelfRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateShelfRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateShelfRequest proto.InternalMessageInfo

func (m *CreateShelfRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *CreateShelfRequest) GetName() *Title {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *CreateShelfRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SaveShelfRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Id                   string         `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId              string         `protobuf:"bytes,3,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	Name                 *Title         `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Locked               bool           `protobuf:"varint,6,opt,name=locked,proto3" json:"locked,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SaveShelfRequest) Reset()         { *m = SaveShelfRequest{} }
func (m *SaveShelfRequest) String() string { return proto.CompactTextString(m) }
func (*SaveShelfRequest) ProtoMessage()    {}
func (*SaveShelfRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_997c08397bcb74ab, []int{4}
}

func (m *SaveShelfRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveShelfRequest.Unmarshal(m, b)
}
func (m *SaveShelfRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveShelfRequest.Marshal(b, m, deterministic)
}
func (m *SaveShelfRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveShelfRequest.Merge(m, src)
}
func (m *SaveShelfRequest) XXX_Size() int {
	return xxx_messageInfo_SaveShelfRequest.Size(m)
}
func (m *SaveShelfRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveShelfRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveShelfRequest proto.InternalMessageInfo

func (m *SaveShelfRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SaveShelfRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SaveShelfRequest) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func (m *SaveShelfRequest) GetName() *Title {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *SaveShelfRequest) GetLocked() bool {
	if m != nil {
		return m.Locked
	}
	return false
}

type DeleteShelfRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Id                   string         `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId              string         `protobuf:"bytes,3,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DeleteShelfRequest) Reset()         { *m = DeleteShelfRequest{} }
func (m *DeleteShelfRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteShelfRequest) ProtoMessage()    {}
func (*DeleteShelfRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_997c08397bcb74ab, []int{5}
}

func (m *DeleteShelfRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteShelfRequest.Unmarshal(m, b)
}
func (m *DeleteShelfRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteShelfRequest.Marshal(b, m, deterministic)
}
func (m *DeleteShelfRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteShelfRequest.Merge(m, src)
}
func (m *DeleteShelfRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteShelfRequest.Size(m)
}
func (m *DeleteShelfRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteShelfRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteShelfRequest proto.InternalMessageInfo

func (m *DeleteShelfRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *DeleteShelfRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteShelfRequest) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func init() {
	proto.RegisterType((*Shelf)(nil), "notekeeper.Shelf")
	proto.RegisterType((*GetShelvesRequest)(nil), "notekeeper.GetShelvesRequest")
	proto.RegisterType((*GetShelvesResponse)(nil), "notekeeper.GetShelvesResponse")
	proto.RegisterType((*CreateShelfRequest)(nil), "notekeeper.CreateShelfRequest")
	proto.RegisterType((*SaveShelfRequest)(nil), "notekeeper.SaveShelfRequest")
	proto.RegisterType((*DeleteShelfRequest)(nil), "notekeeper.DeleteShelfRequest")
}

func init() { proto.RegisterFile("shelf.proto", fileDescriptor_997c08397bcb74ab) }

var fileDescriptor_997c08397bcb74ab = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0xd1, 0x4a, 0xf3, 0x30,
	0x18, 0xfd, 0xd3, 0xad, 0xdd, 0xfe, 0xaf, 0x22, 0x2e, 0x88, 0xc4, 0x5d, 0x95, 0x82, 0x30, 0x10,
	0x06, 0xce, 0x47, 0x50, 0x50, 0xef, 0x46, 0x27, 0xde, 0xd7, 0xe5, 0x1b, 0x1b, 0x6b, 0x9b, 0xae,
	0x49, 0xe7, 0x9d, 0x8f, 0xe4, 0x03, 0xf8, 0x74, 0x92, 0xa4, 0x99, 0xb3, 0xa0, 0x88, 0x82, 0x97,
	0xe7, 0x3b, 0xa7, 0x27, 0xe7, 0x7c, 0x69, 0x20, 0x94, 0x4b, 0xcc, 0x16, 0xe3, 0xb2, 0x12, 0x4a,
	0x50, 0x28, 0x84, 0xc2, 0x35, 0x62, 0x89, 0xd5, 0xf0, 0x60, 0x2e, 0xf2, 0x5c, 0x14, 0x96, 0x19,
	0x86, 0x6a, 0xa5, 0x32, 0xb4, 0x20, 0x7e, 0x25, 0xe0, 0xcf, 0xf4, 0x67, 0xf4, 0x10, 0xbc, 0x15,
	0x67, 0x24, 0x22, 0xa3, 0xff, 0x89, 0xb7, 0xe2, 0xf4, 0x0c, 0xba, 0x45, 0x9a, 0x23, 0xf3, 0x22,
	0x32, 0x0a, 0x27, 0x83, 0xf1, 0xbb, 0xdf, 0xf8, 0x5e, 0x1b, 0x24, 0x86, 0xa6, 0x0c, 0x7a, 0x1c,
	0x17, 0x69, 0x9d, 0x29, 0xd6, 0x8d, 0xc8, 0xa8, 0x9f, 0x38, 0x48, 0x8f, 0xc1, 0x57, 0x55, 0x2a,
	0x97, 0xcc, 0x37, 0x73, 0x0b, 0xe8, 0x09, 0x04, 0x99, 0x98, 0xaf, 0x91, 0xb3, 0xc0, 0x8c, 0x1b,
	0xa4, 0x7d, 0xe6, 0x15, 0xa6, 0x0a, 0x39, 0xeb, 0x99, 0x0c, 0x0e, 0x6a, 0xa6, 0x2e, 0xb9, 0x61,
	0xfa, 0x96, 0x69, 0x60, 0xfc, 0x00, 0x83, 0x1b, 0x54, 0x3a, 0xfe, 0x16, 0x65, 0x82, 0x9b, 0x1a,
	0xa5, 0xa2, 0x17, 0x10, 0x2c, 0x31, 0xe5, 0x58, 0x99, 0x2e, 0xe1, 0xe4, 0x74, 0x3f, 0x79, 0x23,
	0xba, 0x35, 0x82, 0xa4, 0x11, 0x36, 0xd5, 0x3d, 0x57, 0x3d, 0xae, 0x81, 0xee, 0xfb, 0xca, 0x52,
	0x14, 0x12, 0xe9, 0xa4, 0x65, 0x3c, 0xfc, 0x68, 0x6c, 0x55, 0x2d, 0xe7, 0x73, 0xe8, 0x49, 0x6b,
	0xc3, 0xbc, 0xa8, 0xd3, 0xde, 0xa3, 0x59, 0x7c, 0xe2, 0x14, 0xf1, 0x33, 0xd0, 0x2b, 0xd3, 0xd9,
	0xce, 0x7f, 0xde, 0xe7, 0x9b, 0x57, 0x67, 0x6b, 0x77, 0x76, 0xb5, 0x5f, 0x08, 0x1c, 0xcd, 0xd2,
	0xed, 0xaf, 0x8f, 0x6f, 0xad, 0x53, 0x5f, 0xa0, 0x78, 0x2a, 0xb0, 0xba, 0x73, 0x87, 0x39, 0xb8,
	0x0b, 0xea, 0x7f, 0x1d, 0xf4, 0x93, 0x7f, 0x26, 0xde, 0x00, 0xbd, 0xc6, 0x0c, 0xd5, 0xdf, 0x25,
	0x9e, 0xfe, 0x9b, 0x92, 0xc7, 0xc0, 0x3c, 0x9d, 0xcb, 0xb7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x34,
	0x73, 0xa8, 0x56, 0x70, 0x03, 0x00, 0x00,
}
