// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ui_state.proto

package notekeeper

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoadUIStateResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	WindowWidth          int32           `protobuf:"varint,2,opt,name=windowWidth,proto3" json:"windowWidth,omitempty"`
	WindowHeight         int32           `protobuf:"varint,3,opt,name=windowHeight,proto3" json:"windowHeight,omitempty"`
	WindowXPosition      int32           `protobuf:"varint,4,opt,name=windowXPosition,proto3" json:"windowXPosition,omitempty"`
	WindowYPosition      int32           `protobuf:"varint,5,opt,name=windowYPosition,proto3" json:"windowYPosition,omitempty"`
	WindowMaximized      bool            `protobuf:"varint,6,opt,name=windowMaximized,proto3" json:"windowMaximized,omitempty"`
	WindowMinimized      bool            `protobuf:"varint,7,opt,name=windowMinimized,proto3" json:"windowMinimized,omitempty"`
	WindowFullscreen     bool            `protobuf:"varint,8,opt,name=windowFullscreen,proto3" json:"windowFullscreen,omitempty"`
	DisplayWidth         int32           `protobuf:"varint,9,opt,name=displayWidth,proto3" json:"displayWidth,omitempty"`
	DisplayHeight        int32           `protobuf:"varint,10,opt,name=displayHeight,proto3" json:"displayHeight,omitempty"`
	DisplayXPosition     int32           `protobuf:"varint,11,opt,name=displayXPosition,proto3" json:"displayXPosition,omitempty"`
	DisplayYPosition     int32           `protobuf:"varint,12,opt,name=displayYPosition,proto3" json:"displayYPosition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *LoadUIStateResponse) Reset()         { *m = LoadUIStateResponse{} }
func (m *LoadUIStateResponse) String() string { return proto.CompactTextString(m) }
func (*LoadUIStateResponse) ProtoMessage()    {}
func (*LoadUIStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_17510f5609dfdf2a, []int{0}
}

func (m *LoadUIStateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadUIStateResponse.Unmarshal(m, b)
}
func (m *LoadUIStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadUIStateResponse.Marshal(b, m, deterministic)
}
func (m *LoadUIStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadUIStateResponse.Merge(m, src)
}
func (m *LoadUIStateResponse) XXX_Size() int {
	return xxx_messageInfo_LoadUIStateResponse.Size(m)
}
func (m *LoadUIStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadUIStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadUIStateResponse proto.InternalMessageInfo

func (m *LoadUIStateResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *LoadUIStateResponse) GetWindowWidth() int32 {
	if m != nil {
		return m.WindowWidth
	}
	return 0
}

func (m *LoadUIStateResponse) GetWindowHeight() int32 {
	if m != nil {
		return m.WindowHeight
	}
	return 0
}

func (m *LoadUIStateResponse) GetWindowXPosition() int32 {
	if m != nil {
		return m.WindowXPosition
	}
	return 0
}

func (m *LoadUIStateResponse) GetWindowYPosition() int32 {
	if m != nil {
		return m.WindowYPosition
	}
	return 0
}

func (m *LoadUIStateResponse) GetWindowMaximized() bool {
	if m != nil {
		return m.WindowMaximized
	}
	return false
}

func (m *LoadUIStateResponse) GetWindowMinimized() bool {
	if m != nil {
		return m.WindowMinimized
	}
	return false
}

func (m *LoadUIStateResponse) GetWindowFullscreen() bool {
	if m != nil {
		return m.WindowFullscreen
	}
	return false
}

func (m *LoadUIStateResponse) GetDisplayWidth() int32 {
	if m != nil {
		return m.DisplayWidth
	}
	return 0
}

func (m *LoadUIStateResponse) GetDisplayHeight() int32 {
	if m != nil {
		return m.DisplayHeight
	}
	return 0
}

func (m *LoadUIStateResponse) GetDisplayXPosition() int32 {
	if m != nil {
		return m.DisplayXPosition
	}
	return 0
}

func (m *LoadUIStateResponse) GetDisplayYPosition() int32 {
	if m != nil {
		return m.DisplayYPosition
	}
	return 0
}

type SaveUIStateRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	WindowWidth          int32          `protobuf:"varint,2,opt,name=windowWidth,proto3" json:"windowWidth,omitempty"`
	WindowHeight         int32          `protobuf:"varint,3,opt,name=windowHeight,proto3" json:"windowHeight,omitempty"`
	WindowXPosition      int32          `protobuf:"varint,4,opt,name=windowXPosition,proto3" json:"windowXPosition,omitempty"`
	WindowYPosition      int32          `protobuf:"varint,5,opt,name=windowYPosition,proto3" json:"windowYPosition,omitempty"`
	WindowMaximized      bool           `protobuf:"varint,6,opt,name=windowMaximized,proto3" json:"windowMaximized,omitempty"`
	WindowMinimized      bool           `protobuf:"varint,7,opt,name=windowMinimized,proto3" json:"windowMinimized,omitempty"`
	WindowFullscreen     bool           `protobuf:"varint,8,opt,name=windowFullscreen,proto3" json:"windowFullscreen,omitempty"`
	DisplayWidth         int32          `protobuf:"varint,9,opt,name=displayWidth,proto3" json:"displayWidth,omitempty"`
	DisplayHeight        int32          `protobuf:"varint,10,opt,name=displayHeight,proto3" json:"displayHeight,omitempty"`
	DisplayXPosition     int32          `protobuf:"varint,11,opt,name=displayXPosition,proto3" json:"displayXPosition,omitempty"`
	DisplayYPosition     int32          `protobuf:"varint,12,opt,name=displayYPosition,proto3" json:"displayYPosition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SaveUIStateRequest) Reset()         { *m = SaveUIStateRequest{} }
func (m *SaveUIStateRequest) String() string { return proto.CompactTextString(m) }
func (*SaveUIStateRequest) ProtoMessage()    {}
func (*SaveUIStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17510f5609dfdf2a, []int{1}
}

func (m *SaveUIStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveUIStateRequest.Unmarshal(m, b)
}
func (m *SaveUIStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveUIStateRequest.Marshal(b, m, deterministic)
}
func (m *SaveUIStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveUIStateRequest.Merge(m, src)
}
func (m *SaveUIStateRequest) XXX_Size() int {
	return xxx_messageInfo_SaveUIStateRequest.Size(m)
}
func (m *SaveUIStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveUIStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveUIStateRequest proto.InternalMessageInfo

func (m *SaveUIStateRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SaveUIStateRequest) GetWindowWidth() int32 {
	if m != nil {
		return m.WindowWidth
	}
	return 0
}

func (m *SaveUIStateRequest) GetWindowHeight() int32 {
	if m != nil {
		return m.WindowHeight
	}
	return 0
}

func (m *SaveUIStateRequest) GetWindowXPosition() int32 {
	if m != nil {
		return m.WindowXPosition
	}
	return 0
}

func (m *SaveUIStateRequest) GetWindowYPosition() int32 {
	if m != nil {
		return m.WindowYPosition
	}
	return 0
}

func (m *SaveUIStateRequest) GetWindowMaximized() bool {
	if m != nil {
		return m.WindowMaximized
	}
	return false
}

func (m *SaveUIStateRequest) GetWindowMinimized() bool {
	if m != nil {
		return m.WindowMinimized
	}
	return false
}

func (m *SaveUIStateRequest) GetWindowFullscreen() bool {
	if m != nil {
		return m.WindowFullscreen
	}
	return false
}

func (m *SaveUIStateRequest) GetDisplayWidth() int32 {
	if m != nil {
		return m.DisplayWidth
	}
	return 0
}

func (m *SaveUIStateRequest) GetDisplayHeight() int32 {
	if m != nil {
		return m.DisplayHeight
	}
	return 0
}

func (m *SaveUIStateRequest) GetDisplayXPosition() int32 {
	if m != nil {
		return m.DisplayXPosition
	}
	return 0
}

func (m *SaveUIStateRequest) GetDisplayYPosition() int32 {
	if m != nil {
		return m.DisplayYPosition
	}
	return 0
}

func init() {
	proto.RegisterType((*LoadUIStateResponse)(nil), "notekeeper.LoadUIStateResponse")
	proto.RegisterType((*SaveUIStateRequest)(nil), "notekeeper.SaveUIStateRequest")
}

func init() { proto.RegisterFile("ui_state.proto", fileDescriptor_17510f5609dfdf2a) }

var fileDescriptor_17510f5609dfdf2a = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0xd4, 0x4d, 0x4b, 0xc3, 0x30,
	0x18, 0xc0, 0x71, 0xaa, 0xdb, 0x9c, 0xd9, 0x7c, 0x21, 0x5e, 0xe2, 0x4e, 0xa5, 0x78, 0x28, 0x1e,
	0x0a, 0xce, 0xef, 0x20, 0x13, 0x14, 0xa4, 0x43, 0x74, 0x27, 0x89, 0xcb, 0x83, 0x0d, 0xb6, 0x49,
	0x6d, 0x52, 0xa7, 0x5e, 0xc5, 0xef, 0x2d, 0x4d, 0xba, 0xbe, 0x7e, 0x03, 0xf1, 0x98, 0x7f, 0x7f,
	0xb4, 0xe4, 0xe1, 0xa1, 0xe8, 0x30, 0xe7, 0x4f, 0x4a, 0x53, 0x0d, 0x41, 0x9a, 0x49, 0x2d, 0x31,
	0x12, 0x52, 0xc3, 0x2b, 0x40, 0x0a, 0xd9, 0x6c, 0xba, 0x96, 0x49, 0x22, 0x85, 0x7d, 0xe2, 0xfd,
	0x0c, 0xd0, 0xc9, 0x8d, 0xa4, 0xec, 0xfe, 0x7a, 0x59, 0xf8, 0x10, 0x54, 0x2a, 0x85, 0x02, 0x3c,
	0x47, 0xa3, 0x08, 0x28, 0x83, 0x8c, 0x38, 0xae, 0xe3, 0x4f, 0xe6, 0xb3, 0xa0, 0x7e, 0x45, 0xb0,
	0x55, 0x0b, 0x23, 0xc2, 0x52, 0x62, 0x17, 0x4d, 0x36, 0x5c, 0x30, 0xb9, 0x79, 0xe0, 0x4c, 0x47,
	0x64, 0xc7, 0x75, 0xfc, 0x61, 0xd8, 0x4c, 0xd8, 0x43, 0x53, 0x7b, 0x5c, 0x00, 0x7f, 0x89, 0x34,
	0xd9, 0x35, 0xa4, 0xd5, 0xb0, 0x8f, 0x8e, 0xec, 0xf9, 0xf1, 0x4e, 0x2a, 0xae, 0xb9, 0x14, 0x64,
	0x60, 0x58, 0x37, 0xd7, 0x72, 0x55, 0xc9, 0x61, 0x53, 0xae, 0xfa, 0xf2, 0x96, 0x7e, 0xf0, 0x84,
	0x7f, 0x01, 0x23, 0x23, 0xd7, 0xf1, 0xc7, 0x61, 0x37, 0x37, 0x24, 0x17, 0xa5, 0xdc, 0x6b, 0xc9,
	0x6d, 0xc6, 0xe7, 0xe8, 0xd8, 0xa6, 0xab, 0x3c, 0x8e, 0xd5, 0x3a, 0x03, 0x10, 0x64, 0x6c, 0x68,
	0xaf, 0x17, 0xf7, 0x66, 0x5c, 0xa5, 0x31, 0xfd, 0xb4, 0xa3, 0xd9, 0xb7, 0xf7, 0x6e, 0x36, 0x7c,
	0x86, 0x0e, 0xca, 0x73, 0x39, 0x1c, 0x64, 0x50, 0x3b, 0x16, 0x5f, 0x2d, 0x43, 0x3d, 0x9e, 0x89,
	0x81, 0xbd, 0xde, 0xb0, 0xf5, 0x80, 0xa6, 0x2d, 0x5b, 0x75, 0xef, 0x7b, 0x80, 0xf0, 0x92, 0xbe,
	0x43, 0xb5, 0x07, 0x6f, 0x39, 0x28, 0x8d, 0x2f, 0x3a, 0x6b, 0x70, 0xda, 0x5e, 0x03, 0x83, 0xfe,
	0xb7, 0xe0, 0xaf, 0x6c, 0xc1, 0xf3, 0xc8, 0xfc, 0x14, 0x2e, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x41, 0x1a, 0xa7, 0x67, 0x40, 0x04, 0x00, 0x00,
}
