// Code generated by protoc-gen-go. DO NOT EDIT.
// source: workspace.proto

package notekeeper

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("workspace.proto", fileDescriptor_dac718ecaafc2333) }

var fileDescriptor_dac718ecaafc2333 = []byte{
	// 58 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0xcf, 0x2f, 0xca,
	0x2e, 0x2e, 0x48, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xca, 0xcb, 0x2f,
	0x49, 0xcd, 0x4e, 0x4d, 0x2d, 0x48, 0x2d, 0x4a, 0x62, 0x03, 0x0b, 0x19, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x0c, 0xea, 0x8f, 0x5f, 0x25, 0x00, 0x00, 0x00,
}
